//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_PHONGGYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public int MaCheckIn { get; set; }
        public int MaKH { get; set; }
        public System.DateTime ThoiGianVao { get; set; }
        public Nullable<System.DateTime> ThoiGianRa { get; set; }
        public string TrangThai { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
