//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_PHONGGYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauHoTro
    {
        public int MaYC { get; set; }
        public int MaKH { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string LoaiYeuCau { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string PhanHoi { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public Nullable<System.DateTime> NgayXuLy { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
